### ISSUE TITLE
KeystoneTooltip.lua:66: attempt to compare number with nil

### ISSUE THREAD

**Issue by Hollicsh** [drkgreyhawk/KeystoneLoot#27]
18x KeystoneTooltip/KeystoneTooltip.lua:66: attempt to compare number with nil
[string "@KeystoneTooltip/KeystoneTooltip.lua"]:66: in function `GetDungeonReward'
[string "@KeystoneTooltip/KeystoneTooltip.lua"]:36: in function <KeystoneTooltip/KeystoneTooltip.lua:28>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML/ContainerFrame.lua"]:1498: in function `OnUpdate'
[string "@FrameXML/ContainerFrame.lua"]:1465: in function `OnEnter'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1460>
[string "=[C]"]: ?

Locals:
mlvl = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
dungeon_rewards = <table> {
 1 = 402
 2 = 405
 3 = 405
 4 = 408
 5 = 408
 6 = 411
 7 = 411
 8 = 415
 9 = 415
 10 = 418
 11 = 418
 12 = 421
 13 = 421
 14 = 424
 15 = 424
 16 = 428
 17 = 428
 18 = 431
 19 = 431
}

**Comment by drkgreyhawk** [comment]
Do we know what level the key is that is causing this error?

**Comment by Hollicsh** [comment]
Yes. When I hover over +19 Halls of Infusion

**Comment by drkgreyhawk** [comment]
Interesting... I can't seem to recreate it. What language is your client in?

**Comment by Hollicsh** [comment]
Russian client

**Comment by drkgreyhawk** [comment]
I wonder if that has something to do with it. I'll look into it.

**Comment by Hollicsh** [comment]
I reset the key to level 17 and the error stopped getting out о_О

**Comment by drkgreyhawk** [comment]
Well that's certainly odd. I haven't found what's causing the function to get a `nil` value. I did, however, add some slash commands to the addon. Those will be coming out in the next release later this week. I'm going to keep this issue open for now since it wasn't actually fixed.
