### ISSUE TITLE
Ace Locale errors

### ISSUE THREAD

**Issue by yoshimo** [drkgreyhawk/KeystoneLoot#7]
Message: AceLocale-3.0: KeystoneLoot: Missing entry for 'KeystoneLoot: Enabled'
Message: AceLocale-3.0: KeystoneLoot: Missing entry for 'KeystoneLoot: Loaded'

**Comment by drkgreyhawk** [comment]
This requires more information, where are you experiencing these messages? What version are you using? If possible provide [BugSack](https://www.curseforge.com/wow/addons/bugsack) report if you are experiencing this in game.

**Comment by yoshimo** [comment]
## Version: 2.3.2  according to the .toc
Happens somewhere during gamplay, i suspect right after entering the world as the character has no keystones yet.

**Comment by redpril** [comment]
If you create your language locale there will be no errors.

**Comment by drkgreyhawk** [comment]
You can find the localization projects [here](https://www.curseforge.com/wow/addons/keystone-loot/localization), I only know English so any help with other languages is appreciated. As of posting this Russian and Traditional Chinese has been added by the community.
